/**
 *  * JARVIS Core App Logic (Web Audio API + Event Controls)
  */
  const SILENCE_THRESHOLD_MS = 900;

  class JarvisApp {
      constructor() {
              this.isListening = false;
                      this.mediaRecorder = null;
                              this.audioContext = null;
                                      this.analyser = null;
                                              this.silenceTimer = null;
                                                      
                                                              this.initElements();
                                                                      this.bindEvents();
                                                                          }

                                                                              initElements() {
                                                                                      this.btnMic = document.getElementById('btnMic');
                                                                                              this.hud = document.getElementById('reactorHUD');
                                                                                                      this.statusText = document.getElementById('reactorStateText');
                                                                                                              this.captionBox = document.getElementById('captionBox');
                                                                                                                      this.liveAudioBar = document.getElementById('liveAudioBar');
                                                                                                                              this.askInput = document.getElementById('askInput');
                                                                                                                                      this.btnSend = document.getElementById('btnSend');
                                                                                                                                          }

                                                                                                                                              bindEvents() {
                                                                                                                                                      this.btnMic.addEventListener('click', () => this.toggleMicrophone());
                                                                                                                                                              this.btnSend.addEventListener('click', () => this.handleTextSubmit());
                                                                                                                                                                      this.askInput.addEventListener('keydown', (e) => {
                                                                                                                                                                                  if (e.key === 'Enter') this.handleTextSubmit();
                                                                                                                                                                                          });
                                                                                                                                                                                              }

                                                                                                                                                                                                  setReactorState(state) {
                                                                                                                                                                                                          this.hud.className = `reactor ${state}`;
                                                                                                                                                                                                                  this.statusText.textContent = state.toUpperCase();
                                                                                                                                                                                                                      }

                                                                                                                                                                                                                          async toggleMicrophone() {
                                                                                                                                                                                                                                  if (this.isListening) {
                                                                                                                                                                                                                                              this.stopMicrophone();
                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                  await this.startMicrophone();
                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                  async startMicrophone() {
                                                                                                                                                                                                                                                                                          try {
                                                                                                                                                                                                                                                                                                      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
                                                                                                                                                                                                                                                                                                                  this.isListening = true;
                                                                                                                                                                                                                                                                                                                              this.setReactorState('listening');
                                                                                                                                                                                                                                                                                                                                          this.captionBox.textContent = 'Listening...';

                                                                                                                                                                                                                                                                                                                                                      // Web Audio API Setup
                                                                                                                                                                                                                                                                                                                                                                  this.audioContext = new (window.AudioContext || window.webkitAudioContext)();
                                                                                                                                                                                                                                                                                                                                                                              const source = this.audioContext.createMediaStreamSource(stream);
                                                                                                                                                                                                                                                                                                                                                                                          this.analyser = this.audioContext.createAnalyser();
                                                                                                                                                                                                                                                                                                                                                                                                      this.analyser.fftSize = 64;
                                                                                                                                                                                                                                                                                                                                                                                                                  source.connect(this.analyser);

                                                                                                                                                                                                                                                                                                                                                                                                                              this.monitorAudioLevel();
                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                  console.error('Microphone error:', err);
                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.captionBox.textContent = 'Microphone access denied or missing.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                              stopMicrophone() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.isListening = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.setReactorState('idle');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.liveAudioBar.style.width = '0%';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.captionBox.textContent = 'Microphone off.';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (this.audioContext) this.audioContext.close();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              monitorAudioLevel() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      const dataArray = new Uint8Array(this.analyser.frequencyBinCount);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Loop audio monitoring via setInterval per requirement (prevents tab background pause)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const intervalId = setInterval(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (!this.isListening) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          clearInterval(intervalId);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.analyser.getByteFrequencyData(dataArray);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          let sum = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      for (let i = 0; i < dataArray.length; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      sum += dataArray[i];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const average = sum / dataArray.length;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const levelPercentage = Math.min(100, Math.round((average / 128) * 100));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.liveAudioBar.style.width = `${levelPercentage}%`;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Reset silence trigger if sound detected
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (levelPercentage > 15) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          clearTimeout(this.silenceTimer);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.silenceTimer = setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.onSilenceDetected();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, SILENCE_THRESHOLD_MS);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }, 50);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onSilenceDetected() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (this.isListening) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.captionBox.textContent = 'Processing speech turn...';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.setReactorState('thinking');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      // Mock API send transition
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (this.isListening) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.setReactorState('speaking');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.captionBox.textContent = 'JARVIS: "Understood, Mr. Hazil."';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, 1200);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      handleTextSubmit() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const query = this.askInput.value.trim();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (!query) return;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.setReactorState('thinking');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.captionBox.textContent = `Query: "${query}"`;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.askInput.value = '';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.setReactorState('speaking');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.captionBox.textContent = 'JARVIS: "Processing request."';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }, 800);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          window.addEventListener('DOMContentLoaded', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.jarvisApp = new JarvisApp();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
 */