/**
 *  * Canvas-based Force-Directed Graph Rendering Engine
  */
  class GraphEngine {
      constructor(canvasId) {
              this.canvas = document.getElementById(canvasId);
                      this.ctx = this.canvas.getContext('2d');
                              this.nodes = [];
                                      this.links = [];
                                              this.selectedNode = null;
                                                      
                                                              this.resize();
                                                                      window.addEventListener('resize', () => this.resize());
                                                                              this.initDemoData();
                                                                                      this.animate();
                                                                                          }

                                                                                              resize() {
                                                                                                      this.canvas.width = window.innerWidth;
                                                                                                              this.canvas.height = window.innerHeight;
                                                                                                                  }

                                                                                                                      initDemoData() {
                                                                                                                              const categories = ['Client', 'Note', 'Project'];
                                                                                                                                      for (let i = 0; i < 40; i++) {
                                                                                                                                                  this.nodes.push({
                                                                                                                                                                  id: `node-${i}`,
                                                                                                                                                                                  label: `Document ${i + 1}`,
                                                                                                                                                                                                  category: categories[i % categories.length],
                                                                                                                                                                                                                  x: Math.random() * this.canvas.width,
                                                                                                                                                                                                                                  y: Math.random() * this.canvas.height,
                                                                                                                                                                                                                                                  vx: (Math.random() - 0.5) * 0.5,
                                                                                                                                                                                                                                                                  vy: (Math.random() - 0.5) * 0.5,
                                                                                                                                                                                                                                                                                  connections: 0
                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                              // Generate mock connections
                                                                                                                                                                                                                                                                                                                      for (let i = 0; i < this.nodes.length; i++) {
                                                                                                                                                                                                                                                                                                                                  const targetIndex = Math.floor(Math.random() * this.nodes.length);
                                                                                                                                                                                                                                                                                                                                              if (targetIndex !== i) {
                                                                                                                                                                                                                                                                                                                                                              this.links.push({
                                                                                                                                                                                                                                                                                                                                                                                  source: this.nodes[i],
                                                                                                                                                                                                                                                                                                                                                                                                      target: this.nodes[targetIndex]
                                                                                                                                                                                                                                                                                                                                                                                                                      });
                                                                                                                                                                                                                                                                                                                                                                                                                                      this.nodes[i].connections++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.nodes[targetIndex].connections++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  updatePhysics() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Simple positioning & bounds keep-in logic
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.nodes.forEach(node => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              node.x += node.vx;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          node.y += node.vy;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (node.x < 50 || node.x > this.canvas.width - 50) node.vx *= -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  if (node.y < 50 || node.y > this.canvas.height - 50) node.vy *= -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  draw() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  // Draw Links
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.ctx.strokeStyle = 'rgba(255, 255, 255, 0.05)';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.ctx.lineWidth = 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.links.forEach(link => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.ctx.moveTo(link.source.x, link.source.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              this.ctx.lineTo(link.target.x, link.target.y);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.ctx.stroke();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          // Draw Nodes
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.nodes.forEach(node => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              const radius = Math.max(4, Math.min(node.connections * 2, 12));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.ctx.beginPath();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      this.ctx.arc(node.x, node.y, radius, 0, Math.PI * 2);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (node.category === 'Client') this.ctx.fillStyle = '#38bdf8';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          else if (node.category === 'Project') this.ctx.fillStyle = '#34d399';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      else this.ctx.fillStyle = '#a855f7';

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.ctx.fill();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  animate() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          this.updatePhysics();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  this.draw();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          requestAnimationFrame(() => this.animate());
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              // Initialize Graph Engine when window loads
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              window.addEventListener('DOMContentLoaded', () => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  window.graphEngine = new GraphEngine('graphCanvas');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
 */